[package]
name = "zed-glua"
version = "0.1.0"
edition = "2021"
publish = false
license = "GPL-3.0-only"

[lib]
path = "src/glua.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.7.0"
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_path_to_error = "0.1"
